name: artemisbeta.ubuntu_setup.setup_cpp
on: push

jobs:
  molecule:
    runs-on: ubuntu-latest
    steps:
      - name: 🥡 Checkout Repository
        uses: actions/checkout@v4
        with:
          path: "${{ github.repository }}"
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Install dependencies.
        run: pip3 install molecule "molecule-plugins[docker]"
      - name: Install Galaxy dependencies.
        run: ansible-galaxy collection install community.docker
      - name: Run molecule
        run: molecule test --scenario-name ci
        working-directory: ${{ github.repository }}/roles/setup_cpp
